### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by budisentosa** [carpad88/nuxtjs-starter-medusa#1]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/store/products. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 204.

i got cors problem 

i have set .env file 

STORE_CORS=http://localhost:3333

any help pls

**Comment by carpad88** [comment]
@budisentosa be sure that you add the URL where your storefront is running. Is your storefrfont running on `http://localhost:3333/`?

Also, try to restart the Medusa server if you made some change on your `.env` file

**Comment by budisentosa** [comment]
@budisentosa be sure that you add the URL where your storefront is running. Is your storefrfont running on http://localhost:3333/?


Yes

Also, try to restart the Medusa server if you made some change on your .env file

I had

But still

**Comment by carpad88** [comment]
@budisentosa Can you share your `nuxt.config` from the storefront and your `medusa.config` from you're Medusa server to take a look on them?

**Comment by carpad88** [comment]
Close by inactivity
